% рассчёт площадей ячеек
function cellS = calc_square(xNodes, yNodes, Nx, Ny)
  cellS = zeros(Ny, Nx);
  
  for i=1:Ny
    for j=1:Nx
      cellS(i,j) = 0.5*(
        (yNodes(i+1,j)-yNodes(i,j))*(xNodes(i,j+1)-xNodes(i,j))- ...
        (xNodes(i+1, j) - xNodes(i, j))*(yNodes(i, j+1) - yNodes(i, j))+ ...
        (yNodes(i, j+1) - yNodes(i+1, j+1))*...
        (xNodes(i+1, j) - xNodes(i+1, j+1))- ...
        (xNodes(i, j+1) - xNodes(i+1, j+1))* ...
        (yNodes(i+1, j) - yNodes(i+1, j+1)));
    end;
  end;
end
